### ISSUE TITLE
Which path should I fill in the label_file when I trainning LRS2 dataset?

### ISSUE THREAD

**Issue by CindyZyxxxxxx** [georgesterpu/Taris#1]
I have referred `write_records_tcd.py` in your another project `avsr-tf1` to change the path in `write_records.py` for LRS2, and I have got LRS2 datasets, but I couldn't find out the file like `character labels` in https://github.com/georgesterpu/avsr-tf1/tree/master/datasets/tcdtimit/configs 
Looking forward for your reply!

**Comment by CindyZyxxxxxx** [comment]
Because of the wrong label_file, there is sure to have the ValueError in File"Taris/avsr/dataset_writer.py", line 191, in _create_labels_dict
ValueErros: dictionary update sequence element #0 has length 1; 2 is required
So, how should I solve this problem?

Thanks.

**Comment by georgesterpu** [comment]
@ZhangYX-bin 
Thanks for opening the issue.
You would have to write a script and generate that label file for every dataset used with this project.
